name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_c655be65120dba796a7daff3023c59670d1af906
      SUPABASE_DB_PASSWORD: PBLFLu7JVgiPO2Pp
      PROJECT_ID: lratwpruzhuxugatcrxb

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
